name: Validate Workflow Trigger by Issue Template

on:
  issues:
    types: 
      - opened
      - edited

jobs:
  validate-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Validate issue form field
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GHA_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const issueBody = issue.body;
            console.log("issueBody :", issueBody);
            try {
              // Parse issue body as JSON array
              const bodyArray = JSON.parse(issueBody);
              console.log("issueBody :", issueBody);
            }catch (error) {
              console.error(error.message);
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `Error: ${error.message} \n\nPlease provide valid issue details.`
              });

            }
